# Generated by Django 3.1.3 on 2020-12-04 08:27

import App.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('Pregnancies', models.IntegerField(default=0)),
                ('Glucose', models.IntegerField(default=0)),
                ('BP', models.IntegerField(default=0)),
                ('Skinthickness', models.IntegerField(default=0)),
                ('Insulin', models.IntegerField(default=0)),
                ('BMI', models.IntegerField(default=0)),
                ('Diabetic_pf', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=10)),
                ('Res', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Med_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('mediafile', models.FileField(storage=App.storage.OverwriteStorage(), upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
