# Generated by Django 3.1.2 on 2020-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20201204_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabtest',
            name='BMI',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diabtest',
            name='Diabetic_pf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diabtest',
            name='Glucose',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diabtest',
            name='Insulin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diabtest',
            name='Pregnancies',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diabtest',
            name='Skinthickness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diabtest',
            name='age',
            field=models.FloatField(default=10),
        ),
    ]
