# Generated by Django 3.1.2 on 2020-12-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201204_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('age', models.FloatField(default=0)),
                ('anaemia', models.FloatField(default=0)),
                ('creatinine_phosphokinase', models.IntegerField(default=0)),
                ('diabetes', models.FloatField(default=0)),
                ('ejection_fraction', models.FloatField(default=0)),
                ('high_blood_pressure', models.FloatField(default=0)),
                ('platelets', models.FloatField(default=0)),
                ('serum_creatinine', models.FloatField(default=10)),
                ('serum_sodium', models.FloatField(max_length=10, null=True)),
                ('sex', models.FloatField(max_length=10, null=True)),
                ('smoking', models.FloatField(max_length=10, null=True)),
                ('time', models.FloatField(max_length=10, null=True)),
                ('DEATH_EVENT', models.FloatField(max_length=10, null=True)),
            ],
        ),
    ]
