# Generated by Django 3.1.2 on 2020-12-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_hearttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabtest',
            name='Testdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hearttest',
            name='Testdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hearttest',
            name='DEATH_EVENT',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
