# Generated by Django 3.1.2 on 2020-12-05 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201205_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Med_file',
        ),
        migrations.AlterField(
            model_name='diabtest',
            name='Testdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='hearttest',
            name='Testdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
